require('sinatra')
require('sinatra/reloader')
also_reload('lib/**/*.rb')
require('./lib/contact')
require('./lib/address')
require('./lib/email')
require('./lib/phone')

get('/') do
  erb(:index)
end

# Page for creating new contact
get('/contact/new') do
  erb(:new_contact)
end

# Takes data from form
post('/new_contact') do
  @first = params.fetch('first_name')
  @last = params.fetch('last_name')
  @company = params.fetch('company')
  @job_title = params.fetch('job_title')

  Contact.new({:first_name => @first, :last_name => @last, :company => @company, :job_title => @job_title}).save()
  erb(:success)
end

# Lists all contacts
get('/contacts/all') do
  @contacts = Contact.contacts()
  erb(:all_contacts)
end

# Dynamically creates page for contact
  #:id is generated by an each loop that activates the .id() method
get('/contact/:id') do
  @current_contact = Contact.find(params.fetch('id').to_i)
  erb(:contact)
end

# Corresponds to current contact ID
get('/contact/new_address/:id') do
  @current_contact = Contact.find(params.fetch('id').to_i)
  erb(:new_address)
end

# Takes data from form
post('/create_address/:id') do
  @street = params.fetch('street')
  @city = params.fetch('city')
  @state = params.fetch('state')
  @zip = params.fetch('zip')
  @type = params.fetch('type')
  # Uses generated ID to find the current_contact
  @current_contact = Contact.find(params.fetch('id').to_i)
  # Takes parameter variables to generate the address
  current_address = Address.new({:street => @street, :city => @city, :state => @state, :zip => @zip, :type => @type})

  # Adds address to the contact
  @current_contact.add_mailing_address(current_address)

  erb(:success)
end

# id1 corresponds to address.id()
# id2 corresponds to contact.id()
get('/address/:id1/:id2') do
  # Uses generated ID's to find contact and address
  @current_contact = Contact.find(params.fetch('id2').to_i)
  @current_address = @current_contact.find_address(params.fetch('id1').to_i)
  erb(:address)
end

get('/contact/new_phone/:id') do
  @current_contact = Contact.find(params.fetch('id').to_i)
  erb(:new_phone)
end

post('/create_phone/:id') do
  @phone = params.fetch('phone_number').to_i
  @type = params.fetch('phone_type')
  @current_contact = Contact.find(params.fetch('id').to_i)
  current_phone = Phone.new({:phone_number => @phone, :type => @type})
  @current_contact.add_phone_number(current_phone)

  erb(:success)
end

get('/number/:id1/:id2') do
  # Uses generated ID's to find contact and address
  @current_contact = Contact.find(params.fetch('id2').to_i)
  @current_number = @current_contact.find_phone(params.fetch('id1').to_i)
  erb(:phone)
end

get('/contact/new_email/:id') do
  @current_contact = Contact.find(params.fetch('id').to_i)
  erb(:new_email)
end

post('/create_email/:id') do
  @email = params.fetch('email')
  @current_contact = Contact.find(params.fetch('id').to_i)
  current_email = Email.new({:address => @email})
  @current_contact.add_email(current_email)

  erb(:success)
end

get('/email/:id1/:id2') do
  # Uses generated ID's to find contact and address
  @current_contact = Contact.find(params.fetch('id2').to_i)
  @current_email = @current_contact.find_email(params.fetch('id1').to_i)
  erb(:email)
end
